#!/bin/sh

. "lib_common.sh"

help() {
cat << EOF
${progname}: QEMU wrapper with database
ONLY supports x86_64
Data directory: ~/.local/share/sboot

USAGE:
    ${progname} <COMMAND> [OPTIONS] [ARGS...]

COMMANDS:
    install  FILE             Install file (must be in correct format)
    image    [OPTIONS] OS     Manage OS disk images
    remove   [OPTIONS] OS     Remove OSes or files
    boot     [OPTIONS] OS     Boot virtual machine
    list                      List available OSes
    help                      Show this message

IMAGE OPTIONS:
    -r SIZE                   Resize disk (e.g., 20G, +5G)
    -c                        Create file

BOOT OPTIONS:
    -i FILE                   Boot from ISO file
    -e ARGS                   Add extra QEMU arguments (append)
    -a ARGS                   Overwrite all QEMU arguments (replace)

REMOVE OPTIONS:
    -f                        Silent
EOF
exit 0
}

VMSDIR="$HOME/.local/share/sboot"

check_arguments() {
	actual_argc="$1"; shift
	expected_argc="$1"; shift

	[ "${actual_argc}" -ne "${expected_argc}" ] && invalid_use
}

get_file() {
	DIRECTORY="$VMSDIR"
	[ "$1" = "-t" ] && DIRECTORY="$TMPDIR" && shift
	BASEVM="${1}"
	FILE_EXTENSION="${2}"

	echo "${DIRECTORY}"/"${BASEVM}"/"${BASEVM}""${FILE_EXTENSION}"
}

normalize_args() {
	expected_argc="$1"; shift
	optstring="$1"; shift

	OPTIND=1
	flags=""
	while getopts "$optstring" option; do
	case "$option" in
	    "?") invalid_use -h ;;
	    *) flags="$flags -$option $OPTARG" ;;
	esac
	done

	shift $((OPTIND - 1))
	flags=$(printf "%s\n" $flags | sort -u)
	check_arguments $# "$expected_argc"

    	printf '%s\n' $flags
    	printf '%s\n' "$@"
}

vm_list() {
	LIST_DIRECTORY="${1:-.}"
	echo "$LIST_DIRECTORY"

	VM_INDEX=1
	for item in "$LIST_DIRECTORY"/*; do
		[ -e "$item" ] || continue
		name="${item##*/}"
		echo "$VM_INDEX. $name"
		VM_INDEX=$((VM_INDEX + 1))

		if [ -d "$item" ]; then
			for subitem in "$item"/*; do
				[ -e "$subitem" ] || continue
				subname="${subitem##*/}"
				echo "   - $subname"
			done
		fi
	done
}

vm_install() {
	INSTALLEXT=${1##*.}
	INSTALLVM=${1%.*}

	case "$INSTALLEXT" in
	"qcow2"|"iso") ;;
	*) err "invalid extension: $1" ;;
	esac

	subdir="$VMSDIR"/"$INSTALLVM"
	mkdir -pv "$subdir"
	mv "$1" "$subdir"
}

vm_image() {
	[ "$1" = "-c" ] && IMGACTION="create" && shift
	[ "$1" = "-r" ] && IMGACTION="resize" && IMGSIZE="$2" && shift 2

	IMGEXT=${1##*.}
	IMGVM=${1%.*}
 	TARGET_IMG=$(get_file "$IMGVM" ."$IMGEXT")

	case "$IMGEXT" in
	"qcow2") ;;
	*) err "invalid extension: $1" ;;
	esac

	case "$IMGACTION" in
	"resize")
 		check_program "qemu-img"

 		if [ -f "$TARGET_IMG" ]; then
			qemu-img resize "$TARGET_IMG" "$IMGSIZE"
 		else
			err "file not found: $TARGET_IMG"
 		fi
	;;
	"create")
 		check_program "qemu-img"

		mkdir -pv "$(dirname "$TARGET_IMG")"

 		if [ -f "${TARGET_IMG}" ]; then
 			err "file already exists: ${TARGET_IMG}"
 		else
 			qemu-img create -f qcow2 "${TARGET_IMG}" 10G
 		fi
	;;
	*) err "no action specified";;
	esac
}

vm_remove() {
	RMFLAGS="-ri"
	[ "$1" = "-f" ] && RMFLAGS="-rf" && shift
	rm "$RMFLAGS" $(find "$VMSDIR" -name "$1")
}

vm_boot() {
	DEFAULT_ARGS=1
	[ "$1" = "-a" ] && DEFAULT_ARGS=0 && NEW_ARGS="$2" && shift 2
	[ "$1" = "-e" ] && EXTENDED_ARGS="$2" && shift 2
	if [ "$1" = "-i" ]; then
		ISO_FILE=$(get_file ${2%.*} .iso) && shift 2
		EXTENDED_ARGS="$EXTENDED_ARGS -cdrom "${ISO_FILE}" -boot d"
	fi

	QCOW2_FILE=$(get_file "$1" .qcow2)

	if [ "$DEFAULT_ARGS" -eq 1 ]; then
		QEMU_ARGS="-enable-kvm -m 2G -smp 2 -drive file=${QCOW2_FILE},format=qcow2 -net nic -net user"
	else
		QEMU_ARGS="$NEW_ARGS"
	fi

	QEMU_ARGS="$QEMU_ARGS $EXTENDED_ARGS"

	qemu-system-x86_64 $QEMU_ARGS
}

main() {
	if [ $# -eq 0 ]; then
		invalid_use
	fi

	if [ -d "${VMSDIR}" ]; then
		mkdir -pv "${VMSDIR}"
	fi

	ACTION="${1}" && shift
	case "${ACTION}" in
	"install")
		check_arguments $# 1
		vm_install "$1"
	;;
	"image")
		args=$(normalize_args 1 "cr:" "$@")
		[ $? -ne 0 ] && exit 1
		vm_image $args
	;;
	"remove")
		args=$(normalize_args 1 "f" "$@")
		[ $? -ne 0 ] && exit 1
		vm_remove $args
	;;
	"boot")
		args=$(normalize_args 1 "a:e:i:" "$@")
		[ $? -ne 0 ] && exit 1
		vm_boot $args
	;;
	"list")
		check_arguments $# 0
		vm_list "$VMSDIR"
	;;
	"help")
		check_arguments $# 0
		help
	;;
	*) invalid_use ;;
	esac
}

main "${@}"
